module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('image', [
      { id: 1, url: '/banner-1a.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 2, url: '/banner-2a.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 3, url: '/banner-3a.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 4, url: '/category-cake.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 5, url: '/category-vg.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 6, url: '/category-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 7, url: '/category-fry-a.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 8, url: '/category-tea.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 9, url: '/category-rice.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 10, url: '/product-dryfruit@1.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 13, url: '//product-vg@1.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 14, url: '/product-rice@6.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 16, url: '/1@theme.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 17, url: '/2@theme.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 18, url: '/3@theme.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 19, url: '/detail-1@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 20, url: '/detail-2@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 21, url: '/detail-3@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 22, url: '/detail-4@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 23, url: '/detail-5@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 24, url: '/detail-6@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 25, url: '/detail-7@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 26, url: '/detail-8@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 27, url: '/detail-9@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 28, url: '/detail-10@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 29, url: '/detail-11@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 31, url: '/product-rice@1.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 32, url: '/product-tea@1.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 33, url: '/product-dryfruit@2.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 36, url: '/product-dryfruit@3.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 37, url: '/product-dryfruit@4.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 38, url: '/product-dryfruit@5.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 39, url: '/product-dryfruit-a@6.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 40, url: '/product-dryfruit@7.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 41, url: '/product-rice@2.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 42, url: '/product-rice@3.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 43, url: '/product-rice@4.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 44, url: '/product-fry@1.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 45, url: '/product-fry@2.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 46, url: '/product-fry@3.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 47, url: '/product-tea@2.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 48, url: '/product-tea@3.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 49, url: '/1@theme-head.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 50, url: '/2@theme-head.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 51, url: '/3@theme-head.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 52, url: '/product-cake@1.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 53, url: '/product-cake@2.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 54, url: '/product-cake-a@3.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 55, url: '/product-cake-a@4.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 56, url: '/product-dryfruit@8.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 57, url: '/product-fry@4.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 58, url: '/product-fry@5.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 59, url: '/product-rice@5.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 60, url: '/product-rice@7.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 62, url: '/detail-12@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 63, url: '/detail-13@1-dryfruit.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 65, url: '/banner-4a.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 66, url: '/product-vg@4.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 67, url: '/product-vg@5.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 68, url: '/product-vg@2.png', from: 1, created_at: new Date(), updated_at: new Date() },
      { id: 69, url: '/product-vg@3.png', from: 1, created_at: new Date(), updated_at: new Date() }
    ], {})
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('image', null, {})
  }
}
